In [1]:
import tensorflow as tf
import numpy as np

2024-02-20 01:51:07.051558: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-20 01:51:07.074634: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-20 01:51:07.074650: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-20 01:51:07.075534: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-20 01:51:07.079937: I tensorflow/core/platform/cpu_feature_guar

In [11]:
a = tf.constant([[1,2], [3,4]])
b = tf.constant([[5,6], [7,8]])
c = tf.linalg.matmul(a,b)
print('a', a)
print('b', b)
print('a * b = ',c)

a tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
b tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
a * b =  tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
